_target_: imitation.data.rollout.flatten_trajectories
trajectories:
    _target_: numpy.concatenate
    _args_:
    # List of lists: First argument is a list of trajectories to combine
    - - _target_: intrl.common.data.storage.load_trajectories
        paths: ${oc.select:imitation.vars.expert_paths,???}
        pattern: ${oc.select:imitation.vars.expert_file_pattern,???}
        verbose: True
        use_infos: False
        set_fields: Null
        choose_func:
          _target_: intrl.common.utils.random_choice
          _partial_: True
          replace: False
          size: ${oc.select:imitation.vars.expert_size,???}
      - _target_: intrl.common.data.storage.load_trajectories
        paths: ${oc.select:imitation.vars.imperfect_paths,???}
        pattern: ${oc.select:imitation.vars.imperfect_file_pattern,???}
        verbose: True
        use_infos: False
        set_fields: Null
        choose_func:
          _target_: intrl.common.utils.random_choice
          _partial_: True
          replace: False
          size: ${oc.select:imitation.vars.imperfect_size,???}